Description: >

  This template deploys a VPC, 3 pub and private subnets. It deploys an Internet Gateway, with a default 
  route on the public subnets. It deploys a pair of NAT Gateways (one in each
  AZ), and default routes for them in the private subnets.

  It then deploys a highly available ECS cluster using an AutoScaling Group,
  with ECS hosts distributed across multiple Availability Zones.

  3 zones were chosen because every region has at least 3 

Parameters:
  NestedStacksS3Bucket:
    Description: The name of the versioned S3 bucket you created to hold nested stack temlpates
    Type: String
    Default: cf.myezteam.com

  InstanceType:
    Description: Which instance type should we use to build the ECS cluster?
    Type: String
    Default: t3.nano

  ClusterSize:
    Description: How many ECS hosts do you want to initially deploy?
    Type: Number
    Default: 0

  ClusterMinSize:
    Description: Minimum number of ECS hosts to keep around?
    Type: Number
    Default: 0

  ClusterMaxSize:
    Description: Maximum number of ECS hosts to have?
    Type: Number
    Default: 0

  VpcCIDR:
    Type: String
    Default: 12.1.0.0/16

  PublicSubnet1CIDR:
    Type: String
    Default: 12.1.32.0/20
  PublicSubnet2CIDR:
    Type: String
    Default: 12.1.96.0/20
  PublicSubnet3CIDR:
    Type: String
    Default: 12.1.160.0/20

  PrivateSubnet1CIDR:
    Type: String
    Default: 12.1.0.0/19
  PrivateSubnet2CIDR:
    Type: String
    Default: 12.1.64.0/19
  PrivateSubnet3CIDR:
    Type: String
    Default: 12.1.128.0/19

  ECSImageId:
    Description: The AMI ID to use for the ECS instances http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI.html
    Type: String
    Default: ami-0aa9ee1fc70e57450


Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "VPC"
        Parameters:
          - VpcCIDR
          - PublicSubnet1CIDR
          - PublicSubnet2CIDR
          - PublicSubnet3CIDR
          - PrivateSubnet1CIDR
          - PrivateSubnet2CIDR
          - PrivateSubnet3CIDR

Mappings: 
  NestedStacks: 
    infrastructure: 
      "vpc": "vpc/three-sub-nat-gateway.yaml?versionid=0_vmITmAcahQ5_rM13cAazOKX9Xv4UWs"
      "secgroups": "security-groups/ecs-in-vpc.yaml?versionid=.7h9gMk1CKs0FiER_Vc7.RcSSIsI.jOB"
      "ecscluster": "ecs/cluster-in-vpc.yaml?versionid=586nZgVxEsBQ_TSyq.T5XxE74EoNq6pn"

Conditions:
  ClusterSizeNotZero: !Not [ !Equals [ !Ref ClusterSize, 0 ] ]

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 
        - https://s3.${AWS::Region}.amazonaws.com/${NestedStacksS3Bucket}/nested-stacks/${url}
        - { url: !FindInMap [NestedStacks, infrastructure, vpc] }

        # https://s3.amazonaws.com/cf.yourdomain.com/infrastructure/vpc.yaml?versionid=WH_GYYQbsoadVDXO9Lqv0vhBWzpV0raw
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        VpcCIDR: !Ref VpcCIDR
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR
        PublicSubnet3CIDR: !Ref PublicSubnet3CIDR
        PrivateSubnet1CIDR: !Ref PrivateSubnet1CIDR
        PrivateSubnet2CIDR: !Ref PrivateSubnet2CIDR
        PrivateSubnet3CIDR: !Ref PrivateSubnet3CIDR
  SecurityGroups:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 
        - https://s3.${AWS::Region}.amazonaws.com/${NestedStacksS3Bucket}/nested-stacks/${url}
        - { url: !FindInMap [NestedStacks, infrastructure, secgroups] }

        # https://s3.amazonaws.com/cf.yourdomain.com/infrastructure/security-groups.yaml?versionid=BWH8JIRBkP.LggGolE1d6lqUO1_UnQGt
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        VPC: !GetAtt VPC.Outputs.VPC
  ECS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 
        - https://s3.${AWS::Region}.amazonaws.com/${NestedStacksS3Bucket}/nested-stacks/${url}
        - { url: !FindInMap [NestedStacks, infrastructure, ecscluster] }

        # https://s3.amazonaws.com/cf.yourdomain.com/infrastructure/ecs-cluster.yaml?versionid=a7EedtHDRl1jpwm4IWcjdbacOQeBZuUp
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        InstanceType: !Ref InstanceType
        ClusterMinSize: !Ref ClusterMinSize
        ClusterSize: !Ref ClusterSize
        ClusterMaxSize: !Ref ClusterMaxSize
        VPC: !GetAtt VPC.Outputs.VPC
        SecurityGroup: !GetAtt SecurityGroups.Outputs.ECSHostSecurityGroup
        Subnets: !GetAtt VPC.Outputs.PrivateSubnets
        ECSImageId: !Ref ECSImageId

  CPUReservationScaleUpPolicy:
      Type: AWS::AutoScaling::ScalingPolicy
      Condition: ClusterSizeNotZero
      Properties:
        AdjustmentType: ChangeInCapacity
        AutoScalingGroupName: !GetAtt ECS.Outputs.ECSAutoScalingGroup
        Cooldown: '1800'
        ScalingAdjustment: '1'

  # CPUReservationHighAlert:
  #     Type: AWS::CloudWatch::Alarm
  #     Properties:
  #       EvaluationPeriods: '1'
  #       Statistic: Maximum
  #       Threshold: '70'
  #       Period: '60'
  #       AlarmActions:
  #         - !Ref CPUReservationScaleUpPolicy
  #       Dimensions:
  #         - Name: ClusterName
  #           Value: !GetAtt ECS.Outputs.Cluster
  #       ComparisonOperator: GreaterThanThreshold
  #       MetricName: CPUReservation
  #       Namespace: AWS/ECS

  CPUReservationScaleDownPolicy:
      Type: AWS::AutoScaling::ScalingPolicy
      Condition: ClusterSizeNotZero
      Properties:
        AdjustmentType: ChangeInCapacity
        AutoScalingGroupName: !GetAtt ECS.Outputs.ECSAutoScalingGroup
        Cooldown: '900'
        ScalingAdjustment: '-1'

  # CPUReservationLowAlert:
  #     Type: AWS::CloudWatch::Alarm
  #     Properties:
  #       EvaluationPeriods: '1'
  #       Statistic: Maximum
  #       Threshold: '60'
  #       Period: '60'
  #       AlarmActions:
  #         - !Ref CPUReservationScaleDownPolicy
  #       Dimensions:
  #         - Name: ClusterName
  #           Value: !GetAtt ECS.Outputs.Cluster
  #       ComparisonOperator: LessThanThreshold
  #       MetricName: CPUReservation
  #       Namespace: AWS/ECS

Outputs:
  Version:
    Description: ECS cluster in a VPC
    Value: 1.0.0

  VpcCIDR: 
    Description: CIDR block for the VPC
    Value: !Ref VpcCIDR
    Export:
      Name: !Sub "${AWS::StackName}-VpcCidr"
